### ISSUE TITLE
option to disable autosave

### ISSUE THREAD

**Issue by BimbaLaszlo** [stefandtw/quickfix-reflector.vim#11]
I like to check the modifications in the buffers before saving them, but the plugin automatically writes those. Is it possible to disable this behavior?

**Comment by stefandtw** [comment]
You can now configure
'''
let g:qf_write_changes = 0
'''

With the option, it seems the quickfix window is cleared after you write 
a modified buffer. I don't really know how to fix that. Give the option 
a try and let me know if it's helpful for you!

**Comment by BimbaLaszlo** [comment]
It works fine for me. I think the clearing of quickfix is done by plugin or autocommand in your _.vimrc_. Try it out with the minimum settings:

Create a minimal _.vimrc_, for example _~/.vimrc_mini_ with this content:

    set nocompatible
    filetype plugin indent on
    syntax on
    set runtimepath+=$HOME/.vim_mini

    let g:qf_write_changes = 0

Copy the files from the plugin's dir to _~/.vim_mini_.

Run Vim with the newly created rc file (and disable _.gvimrc_):

    gvim -u ~/.vimrc_mini -U NONE

The plugin should work fine for You too.

**Comment by stefandtw** [comment]
You're right. Works fine without my vimrc.
