### ISSUE TITLE
problem if the line is longer then 181 chars

### ISSUE THREAD

**Issue by BimbaLaszlo** [stefandtw/quickfix-reflector.vim#12]
Modifying a long line via quickfix-reflector is buggy for me. As i can see, the edge of it is around 181 chars. For example:

Save this to a file:

```
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901
```

`:vimgrep 123 FILE | copen`, add some characters to the end of the line, then save the quifix buffer. Modify again without closing the quickfix, then save it again.

For me it produces this kind of problems:
* Adds the first modification to the end of the line.
* Randomizes the changed part.

#### System info

Version of plugin: baf6012
Vim 7.4.803, self build; [output of `:version`](https://gist.github.com/BimbaLaszlo/417f0bfd1ee24b68ac0c)
Operating system: Windows 7

**Comment by stefandtw** [comment]
Should be fixed now. If you are working with very long lines, watch out! Vim will sometimes automatically cut off a part of the line in the quickfix buffer, if the line is very long.

**Comment by BimbaLaszlo** [comment]
Thanks for the quick fix. :) A tip to the documentation: I opening the quickfix window via autocommand:

```vim
autocmd  vimrc  QuickFixCmdPost  *  nested botright cwindow
```

If I omitting the `nested` modifier, then the quickfix is opening, but the plugin will not start until I manually call `:copen` or `cwindow`.
