### ISSUE TITLE
Indentation removed on save

### ISSUE THREAD

**Issue by smichaud** [stefandtw/quickfix-reflector.vim#13]
I don't know if I am the only one experiencing this problem, but when I make changes in the Quick Fix window and I saw, it removes the indentation at the beginning of the line...

**Comment by stefandtw** [comment]
Thanks for the report! Should be fixed now.

**Comment by smichaud** [comment]
Works like a charm ! Thanks for the quick fix.
You have an awesome plugin by the way.

**Comment by stefandtw** [comment]
Thank you :)
