### ISSUE TITLE
Undefined variable s:qfBufferLines

### ISSUE THREAD

**Issue by Konfekt** [stefandtw/quickfix-reflector.vim#16]
On saving `~/.config/.vim/settings/quickfix-reflector.vim` the following error is thrown.

```vim
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/.config/.vim/settings/quickfix-reflector.vim" 10L, 323C
Error detected while processing function <SNR>164_OnWrite:
line    4:
E121: Undefined variable: s:qfBufferLines
E116: Invalid arguments for function copy(s:qfBufferLines)
E15: Invalid expression: copy(s:qfBufferLines)
```

This does not happen without the `quickfix-reflector.vim` plugin.

**Comment by stefandtw** [comment]
An autocmd was using a wildcard and matched the file because it had `quickfix-` in the name. The wildcard is now removed.

**Comment by Konfekt** [comment]
Yep, thanks for fixing it!
