### ISSUE TITLE
Is it possible to do multi-line edits?

### ISSUE THREAD

**Issue by justrajdeep** [stefandtw/quickfix-reflector.vim#21]
Hi 

Great plugin!!!

This might be an enhancement request, but is it possible to add multiple lines from the qf window?

For example i want to change a single line into multiple lines from the qf window itself. Is it possible to do that?

Thanks

**Comment by stefandtw** [comment]
As I mentioned in issue #20, handling multiple lines in the quickfix window would probably make the code more complex, so I'm hesitant to work on that. That said, if someone made a pull request with a simple solution to allow line-breaks, I would accept it.

Meanwhile, maybe you could use the `:cdo` command that was added to Vim some time ago. It operates on each quickfix entry. You can add a line like this:

    cdo s/$/\rnew_line/g | w

There is also the `:cfdo` command, which operates on every file in the quickfix list.

**Comment by justrajdeep** [comment]
Thanks :)
