### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by smichaud** [stefandtw/quickfix-reflector.vim#24]
I have quickfix-reflector.vim installed using Vundle. I remember it was working, but for some reason it is not working anymore... I updated the plugin.

I get => E21: Cannot make changes, 'modifiable' is off.
I have set my .vimrc with:
```
let g:qf_modifiable = 1
let g:qf_write_changes = 1
```

Even if I use `:set ma`, it does not work.

**Comment by stefandtw** [comment]
Some ideas and questions to narrow things down.

* Start Vim with a fresh .vimrc only containing quickfix-reflector. See if the problem persists.
* When exactly does the error occur?
* I assume it is the quickfix buffer that's not modifiable. Is that correct, or is it another buffer? If another, could there be a valid reason why it's not modifiable?
* After the error occurs, does `:messages` offer any relevant output?
* What version of Vim are you using?

**Comment by smichaud** [comment]
Thanks for the quick answer.

I overwrote my .vimrc trying to find the problem, but I overwrote it by mistake. So I checkout my latest version from git. I commented all my plugins and tried to find which one caused the problem. They are now all reactivated and quickfix-reflector works... So I have no clue what was causing the problem. 

I realized that python-mode require a "git submodule update --init --recursive" during the process, so I guess it was worth the work.  

Cheers

**Comment by smichaud** [comment]
I faced the same problem after reinstalling my system. 
I guess there is  a problem with my configuration (probably caused by the snippet below), but it works by simply closing / reopening the Quickfix window.

```
command -bang -nargs=? QFix call QFixToggle(<bang>0)
function! QFixToggle(forced)
  if exists("g:qfix_win") && a:forced == 0
    cclose
    unlet g:qfix_win
  else
    botright copen 10
    let g:qfix_win = bufnr("$")
  endif
endfunction
nmap <silent> \ :QFix<CR>
```
