### ISSUE TITLE
Prevent quickfix buffer to write to a file

### ISSUE THREAD

**Issue by jeromedalbert** [stefandtw/quickfix-reflector.vim#26]
I have this handy bit of code that autowrites files when focus is lost:

```vim
augroup improved_autowrite
  autocmd!
  autocmd FocusLost,BufLeave * call Autowrite()
augroup end

function! Autowrite()
  silent! wa
endfunction
```

However, this also writes the quickfix buffer to a file if I have it open and change focus. For now I was able to mitigate with 

```vim
function! Autowrite()
  if bufname('%') =~ 'quickfix-' | return | endif
  silent! wa
endfunction
```

But this only works if the current buffer is the quickfix list. If I switch to another buffer, it will still write the file.

Is there some way to prevent this? Maybe somehow prevent the quickfix list to ever be written to a file?

**Comment by stefandtw** [comment]
Here are two things you could try:

- Use `:w` instead of `:wa` and keep excluding `quickfix-` buffer names. Should still work. Assuming you don't use operations that modify buffers in multiple windows simultaneously.
- Use `:update` instead of `:write`. If you absolutely need to write buffers in multiple windows, you could do `:windo update`.

**Comment by jeromedalbert** [comment]
Thanks for the pointers!

I want to keep using `:wa` so that autowriting works even when switching tabs. And `windo :update` will sometimes write to the quicklist buffer. So I modified my function with the following code:

```vim
function! Autowrite()
  for tabnum in range(tabpagenr('$'))
    for bufnum in tabpagebuflist(tabnum + 1)
      if bufname(bufnum) =~ '^quickfix-' | return | endif
    endfor
  endfor
  silent! wa
endfunction
```

This disables autowrite if the quickfix list is opened anywhere in Vim. This is good enough behavior for me, as I never leave the quickfix list open for very long anyways. 👍
