### ISSUE TITLE
Neovim support?

### ISSUE THREAD

**Issue by phylome** [stefandtw/quickfix-reflector.vim#31]
I like this plugin a lot. However, it seems not to work for me in Neovim, the quickfix list keeps being `modifiable off`. Is this plugin supposed to work with Neovim? Is there a chance for an update on that?

**Comment by stefandtw** [comment]
Personally I don't use Neovim. However, last time I checked, it did work there.

Please check `:messages`. Also post your Neovim version.

Ideally you could temporarily disable any other plug-ins and try again to see if one of them interferes.

**Comment by phylome** [comment]
Thanks for the reply and hint. I'm using Neovim 0.4.3:

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DM
IN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DEC
LARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/
build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

I followed your suggestion, starting with deactivating all plugins except for the reflector. That worked. After successively adding all the other plugins, I'm surprised that everything still works. I cannot say which plugin did interfere yet. Problem seems to be resolved, at least for the time being.
Thanks again!
