### ISSUE TITLE
Make qf-window modifiable only on demand

### ISSUE THREAD

**Issue by Konfekt** [stefandtw/quickfix-reflector.vim#6]
How about an option to leave the qfwindow nonmodifiable by default ? People might use autocmds executed if a buffer is nonmodifiable. 

Then a map could make it modifiable to use qf-reflector.

**Comment by stefandtw** [comment]
Can you give an example of such an autocommand? If you want things triggered on opening a quickfix window you can listen to events on the buffer "quickfix" instead.

**Comment by Konfekt** [comment]
For example, I find 
```
autocmd bufwinenter * if nonmodifiable | nnoremap <buffer> q :q<cr> | endif
```
convenient.

**Comment by Konfekt** [comment]
Of course, after installing your plugin one could work around every such instance.

But perhaps there are other good reasons for the qfwindow being nonmodifiable by default, so perhaps some find it safer only to make it modifiable when they are about to modify it.

**Comment by stefandtw** [comment]
You can now set
```
g:qf_modifiable=0
```
in your vimrc.

To edit the quickfix buffer, set the 'modifiable' option manually or map it to a key.

**Comment by Konfekt** [comment]
Perfect.

**Comment by Konfekt** [comment]
By the way, `autocmd FileType qf nnoremap <buffer> r :set modifiable<cr>` suggests itself.

**Comment by Konfekt** [comment]
I take that back. Now editing by `r` afterwards is impossible.
