### ISSUE TITLE
Get [ERROR] on successfully applied change when file used for cgetfile is open in a split

### ISSUE THREAD

**Issue by idbrii** [stefandtw/quickfix-reflector.vim#8]
Using 3958eff and with nearly the same steps as #7, I get `c.txt|1| [ERROR] some text here` in my quickfix, but the change is correctly applied. The only difference is that I have c.out open in a split.

Here's exactly what I'm doing (same files as #7):

    gvim -Nu NONE +'source ~/.vim/bundle/sensible/plugin/sensible.vim' +'source ~/.vim/bundle/quickfix-reflector/plugin/quickfix-reflector.vim'
    :e /temp/c.out | split /temp/c.txt | compiler msvc | cgetfile /temp/c.out | copen
    Change 'some' to 'more' and :w

This seems pretty minor (since you must have the quickfix log file open and have the quickfix open at the same time), so I'm fine with closing as wontfix.

**Comment by stefandtw** [comment]
Thanks for all the well written bug reports!

Unfortunately I can't reproduce this one. I used your instructions and the text got replaced without errors. Are you sure `c.txt` wasn't already modified before you opened it, maybe from a previous change?

**Comment by idbrii** [comment]
I tried my steps again and can't reproduce. I guess you're right it was modified from a previous change.
